(function(){
"use strict";var sl=false;
function getEl(id){return document.getElementById(id);}
function setText(id,v){var e=getEl(id);if(e)e.textContent=v;}
function getSym(){var e=getEl("symbolSelect");return e?e.value:"BTCUSDT";}
function getInt(){var e=getEl("intervalSelect");return e?e.value:"15m";}
var sidebarOpen=false;
function openSidebar(tab){var sb=getEl("signalSidebar"),ov=getEl("sidebarOverlay"),btn=getEl("sidebarToggle");if(!sb||!ov)return;sb.classList.add("open");ov.classList.add("active");if(btn)btn.classList.add("active");sidebarOpen=true;if(tab)switchTab(tab);}
function closeSidebar(){var sb=getEl("signalSidebar"),ov=getEl("sidebarOverlay"),btn=getEl("sidebarToggle");if(!sb||!ov)return;sb.classList.remove("open");ov.classList.remove("active");if(btn)btn.classList.remove("active");sidebarOpen=false;}
function switchTab(tabId){var tabs=document.querySelectorAll(".ss-tab");for(var i=0;i<tabs.length;i++)tabs[i].classList.toggle("active",tabs[i].getAttribute("data-stab")===tabId);var panels=document.querySelectorAll(".ss-panel");for(var i=0;i<panels.length;i++)panels[i].classList.remove("active");if(tabId==="live-signals"){var p=getEl("panel-live-signals");if(p)p.classList.add("active");fetchSignal();}else if(tabId==="edge-stats"){var p=getEl("panel-backtest-confidence");if(p)p.classList.add("active");}}
async function fetchSignal(){if(sl)return;sl=true;try{var r=await fetch("/api/signal",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol:getSym(),interval:getInt()})});var d=await r.json();if(d.success)updateLiveSignalsPanel(d);else showError(d.error||"Unknown error");}catch(e){console.warn("Signal failed:",e);showError("Connection failed");}finally{sl=false;}}
function showError(msg){var el=getEl("lsSignalLabel");if(el){el.textContent="Error";el.style.color="#f43f5e";}var desc=getEl("lsSignalDesc");if(desc){desc.textContent=msg;desc.style.color="#f43f5e";}}
function updateLiveSignalsPanel(d){var isTrade=d.signal==="TRADE",isLong=d.direction==="long";setText("lsSignalIcon",isTrade?(isLong?">":"<"):"||");var label=getEl("lsSignalLabel");if(label){label.textContent=isTrade?(isLong?"LONG SIGNAL":"SHORT SIGNAL"):"No Active Signal";label.style.color=isTrade?(isLong?"#10b981":"#f43f5e"):"var(--text-muted)";}setText("lsSignalDesc",isTrade?(d.confidence||"Signal detected"):"Run a scan");setText("lsDirValue",isTrade?d.direction.toUpperCase():"---");setText("lsConfValue",d.confidence||"---");if(d.entry)setText("lsEntry","$"+Number(d.entry).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}));if(d.sl)setText("lsSL","$"+Number(d.sl).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}));if(d.tp)setText("lsTP","$"+Number(d.tp).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}));setText("lsRR",d.rr?"1:"+Number(d.rr).toFixed(1):"---");setText("lsSetupTime",d.timestamp||"---");updateComponents(d.components||[]);updateDeltaPatterns(d.deltaPatterns||[]);updateReasoning(d.reasoning||[]);var badge=getEl("liveSignalBadge");if(badge){badge.textContent=d.signal||"---";badge.style.background=isTrade?"rgba(16,185,129,0.2)":"rgba(74,84,120,0.2)";badge.style.color=isTrade?"#10b981":"#4a5478";}}
function updateComponents(c){var el=getEl("lsComponents");if(!el)return;if(!c.length){el.innerHTML="<div class=ls-comp-empty>No components active</div>";return;}var h="";for(var i=0;i<c.length;i++){var x=c[i],active=x.active||x.score>0,color=active?"#10b981":"#475569",sc=x.score?(x.score*100).toFixed(0)+"%":"0%";h+="<div class=ls-comp-card>"+(active?"<div class=ls-comp-header><span class=ls-comp-name>"+(x.name||x.component||"?")+"</span><span class=ls-comp-signal style=color:"+color+">ACTIVE</span></div>":"<div class=ls-comp-header><span class=ls-comp-name>"+(x.name||x.component||"?")+"</span><span class=ls-comp-signal style=color:"+color+">INACTIVE</span></div>")+"<div class=ls-comp-score>"+sc+" confidence</div><div class=ls-comp-bar><div class=ls-comp-bar-fill style=width:"+sc+";background:"+color+"></div></div></div>";}el.innerHTML=h;}
function updateDeltaPatterns(p){var el=getEl("lsDeltaPatterns");if(!el)return;if(!p.length){el.innerHTML="<div style=color:var(--text-muted);font-size:12px;padding:12px>No delta patterns active</div>";return;}var h="";for(var i=0;i<p.length;i++){var x=p[i],color=x.direction==="bullish"?"#10b981":x.direction==="bearish"?"#f43f5e":"#f59e0b";h+="<div class=ls-delta-card style=border-left-color:"+color+"><div class=ls-delta-name>"+(x.name||x.type||"Pattern")+"</div><div class=ls-delta-desc>"+(x.description||x.detail||"")+"</div></div>";}el.innerHTML=h;}
function updateReasoning(r){var el=getEl("lsReasoning");if(!el)return;if(!r.length){el.innerHTML="<div class=ls-rule><span class=ls-rule-num>1</span><span>Run a scan to generate a signal</span></div>";return;}var h="";for(var i=0;i<r.length;i++){var t=typeof r[i]==="string"?r[i]:(r[i].text||r[i].message||JSON.stringify(r[i]));h+="<div class=ls-rule><span class=ls-rule-num>"+(i+1)+"</span><span>"+t+"</span></div>";}el.innerHTML=h;}
function init(){var btn=getEl("sidebarToggle");if(btn)btn.addEventListener("click",function(){if(sidebarOpen)closeSidebar();else openSidebar("live-signals");});var cb=getEl("ssClose");if(cb)cb.addEventListener("click",closeSidebar);var ov=getEl("sidebarOverlay");if(ov)ov.addEventListener("click",closeSidebar);var tabs=document.querySelectorAll(".ss-tab");for(var i=0;i<tabs.length;i++)tabs[i].addEventListener("click",function(){switchTab(this.getAttribute("data-stab"));});document.addEventListener("keydown",function(e){if(e.key==="Escape"&&sidebarOpen)closeSidebar();});}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();